import { io } from 'socket.io-client';
import React from 'react';
import Head from 'next/head';

import type { NextPage } from 'next';

import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <h1>Gartic Show Clone</h1>
        <p>
          Мини-клон gartic show <br /> Next JS | Nest JS | Socket.IO
        </p>
        <button className={styles.startBtn}>Создать игру</button>
      </div>
    </div>
  );
};

export default Home;
